paths:
  /certificateBasedAuthConfiguration:
    description: Provides operations to manage the collection of certificateBasedAuthConfiguration entities.
    get:
      tags:
        - certificateBasedAuthConfiguration.certificateBasedAuthConfiguration
      summary: Get entities from certificateBasedAuthConfiguration
      operationId: certificateBasedAuthConfiguration.certificateBasedAuthConfiguration.ListCertificateBasedAuthConfiguration
      parameters:
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        2XX:
          $ref: '#/components/responses/microsoft.graph.certificateBasedAuthConfigurationCollectionResponse'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-pageable:
        nextLinkName: '@odata.nextLink'
        operationName: listMore
      x-ms-docs-operation-type: operation
    post:
      tags:
        - certificateBasedAuthConfiguration.certificateBasedAuthConfiguration
      summary: Add new entity to certificateBasedAuthConfiguration
      operationId: certificateBasedAuthConfiguration.certificateBasedAuthConfiguration.CreateCertificateBasedAuthConfiguration
      requestBody:
        description: New entity
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.certificateBasedAuthConfiguration'
        required: true
      responses:
        2XX:
          description: Created entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.certificateBasedAuthConfiguration'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/certificateBasedAuthConfiguration/{certificateBasedAuthConfiguration-id}':
    description: Provides operations to manage the collection of certificateBasedAuthConfiguration entities.
    get:
      tags:
        - certificateBasedAuthConfiguration.certificateBasedAuthConfiguration
      summary: Get entity from certificateBasedAuthConfiguration by key
      operationId: certificateBasedAuthConfiguration.certificateBasedAuthConfiguration.GetCertificateBasedAuthConfiguration
      parameters:
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        2XX:
          description: Retrieved entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.certificateBasedAuthConfiguration'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    patch:
      tags:
        - certificateBasedAuthConfiguration.certificateBasedAuthConfiguration
      summary: Update entity in certificateBasedAuthConfiguration
      operationId: certificateBasedAuthConfiguration.certificateBasedAuthConfiguration.UpdateCertificateBasedAuthConfiguration
      requestBody:
        description: New property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.certificateBasedAuthConfiguration'
        required: true
      responses:
        2XX:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.certificateBasedAuthConfiguration'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    delete:
      tags:
        - certificateBasedAuthConfiguration.certificateBasedAuthConfiguration
      summary: Delete entity from certificateBasedAuthConfiguration
      operationId: certificateBasedAuthConfiguration.certificateBasedAuthConfiguration.DeleteCertificateBasedAuthConfiguration
      parameters:
        - name: If-Match
          in: header
          description: ETag
          schema:
            type: string
      responses:
        '204':
          description: Success
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    parameters:
      - name: certificateBasedAuthConfiguration-id
        in: path
        description: The unique identifier of certificateBasedAuthConfiguration
        required: true
        schema:
          type: string
        x-ms-docs-key-type: certificateBasedAuthConfiguration
  /certificateBasedAuthConfiguration/$count:
    description: Provides operations to count the resources in the collection.
    get:
      tags:
        - certificateBasedAuthConfiguration.certificateBasedAuthConfiguration
      summary: Get the number of the resource
      operationId: certificateBasedAuthConfiguration.GetCount-e291
      parameters:
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
      responses:
        2XX:
          $ref: '#/components/responses/ODataCountResponse'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
