paths:
  /groupSettings:
    description: Provides operations to manage the collection of groupSetting entities.
    get:
      tags:
        - groupSettings.groupSetting
      summary: List settings
      description: Retrieve a list of tenant-level or group-specific group settings objects.
      externalDocs:
        description: Find more info here
        url: https://learn.microsoft.com/graph/api/group-list-settings?view=graph-rest-1.0
      operationId: groupSettings.groupSetting.ListGroupSetting
      parameters:
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        2XX:
          $ref: '#/components/responses/microsoft.graph.groupSettingCollectionResponse'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-pageable:
        nextLinkName: '@odata.nextLink'
        operationName: listMore
      x-ms-docs-operation-type: operation
    post:
      tags:
        - groupSettings.groupSetting
      summary: Create settings
      description: 'Create a new group setting based on the templates available in groupSettingTemplates. These settings can be at the tenant-level or at the group level. Group settings apply to only Microsoft 365 groups. The template named Group.Unified can be used to configure tenant-wide Microsoft 365 group settings, while the template named Group.Unified.Guest can be used to configure group-specific settings.'
      externalDocs:
        description: Find more info here
        url: https://learn.microsoft.com/graph/api/group-post-settings?view=graph-rest-1.0
      operationId: groupSettings.groupSetting.CreateGroupSetting
      requestBody:
        description: New entity
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.groupSetting'
        required: true
      responses:
        2XX:
          description: Created entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.groupSetting'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/groupSettings/{groupSetting-id}':
    description: Provides operations to manage the collection of groupSetting entities.
    get:
      tags:
        - groupSettings.groupSetting
      summary: Get groupSetting
      description: Retrieve the properties of a specific group setting object. The setting can be a tenant-level or group-specific setting.
      externalDocs:
        description: Find more info here
        url: https://learn.microsoft.com/graph/api/groupsetting-get?view=graph-rest-1.0
      operationId: groupSettings.groupSetting.GetGroupSetting
      parameters:
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        2XX:
          description: Retrieved entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.groupSetting'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    patch:
      tags:
        - groupSettings.groupSetting
      summary: Update groupSetting
      description: Update the properties of a groupSetting object for tenant-wide group settings or a specific group setting.
      externalDocs:
        description: Find more info here
        url: https://learn.microsoft.com/graph/api/groupsetting-update?view=graph-rest-1.0
      operationId: groupSettings.groupSetting.UpdateGroupSetting
      requestBody:
        description: New property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.groupSetting'
        required: true
      responses:
        2XX:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.groupSetting'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    delete:
      tags:
        - groupSettings.groupSetting
      summary: Delete a group setting
      description: Delete a tenant-level or group-specific groupSetting object.
      externalDocs:
        description: Find more info here
        url: https://learn.microsoft.com/graph/api/groupsetting-delete?view=graph-rest-1.0
      operationId: groupSettings.groupSetting.DeleteGroupSetting
      parameters:
        - name: If-Match
          in: header
          description: ETag
          schema:
            type: string
      responses:
        '204':
          description: Success
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    parameters:
      - name: groupSetting-id
        in: path
        description: The unique identifier of groupSetting
        required: true
        schema:
          type: string
        x-ms-docs-key-type: groupSetting
  /groupSettings/$count:
    description: Provides operations to count the resources in the collection.
    get:
      tags:
        - groupSettings.groupSetting
      summary: Get the number of the resource
      operationId: groupSettings.GetCount-d8de
      parameters:
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
      responses:
        2XX:
          $ref: '#/components/responses/ODataCountResponse'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
