paths:
  /authenticationMethodConfigurations:
    description: Provides operations to manage the collection of authenticationMethodConfiguration entities.
    get:
      tags:
        - authenticationMethodConfigurations.authenticationMethodConfiguration
      summary: Get entities from authenticationMethodConfigurations
      operationId: authenticationMethodConfigurations.authenticationMethodConfiguration.ListAuthenticationMethodConfiguration
      parameters:
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        2XX:
          $ref: '#/components/responses/microsoft.graph.authenticationMethodConfigurationCollectionResponse'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-pageable:
        nextLinkName: '@odata.nextLink'
        operationName: listMore
      x-ms-docs-operation-type: operation
    post:
      tags:
        - authenticationMethodConfigurations.authenticationMethodConfiguration
      summary: Add new entity to authenticationMethodConfigurations
      operationId: authenticationMethodConfigurations.authenticationMethodConfiguration.CreateAuthenticationMethodConfiguration
      requestBody:
        description: New entity
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.authenticationMethodConfiguration'
        required: true
      responses:
        2XX:
          description: Created entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.authenticationMethodConfiguration'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/authenticationMethodConfigurations/{authenticationMethodConfiguration-id}':
    description: Provides operations to manage the collection of authenticationMethodConfiguration entities.
    get:
      tags:
        - authenticationMethodConfigurations.authenticationMethodConfiguration
      summary: Get entity from authenticationMethodConfigurations by key
      operationId: authenticationMethodConfigurations.authenticationMethodConfiguration.GetAuthenticationMethodConfiguration
      parameters:
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        2XX:
          description: Retrieved entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.authenticationMethodConfiguration'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    patch:
      tags:
        - authenticationMethodConfigurations.authenticationMethodConfiguration
      summary: Update entity in authenticationMethodConfigurations
      operationId: authenticationMethodConfigurations.authenticationMethodConfiguration.UpdateAuthenticationMethodConfiguration
      requestBody:
        description: New property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.authenticationMethodConfiguration'
        required: true
      responses:
        2XX:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.authenticationMethodConfiguration'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    delete:
      tags:
        - authenticationMethodConfigurations.authenticationMethodConfiguration
      summary: Delete entity from authenticationMethodConfigurations
      operationId: authenticationMethodConfigurations.authenticationMethodConfiguration.DeleteAuthenticationMethodConfiguration
      parameters:
        - name: If-Match
          in: header
          description: ETag
          schema:
            type: string
      responses:
        '204':
          description: Success
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    parameters:
      - name: authenticationMethodConfiguration-id
        in: path
        description: The unique identifier of authenticationMethodConfiguration
        required: true
        schema:
          type: string
        x-ms-docs-key-type: authenticationMethodConfiguration
  /authenticationMethodConfigurations/$count:
    description: Provides operations to count the resources in the collection.
    get:
      tags:
        - authenticationMethodConfigurations.authenticationMethodConfiguration
      summary: Get the number of the resource
      operationId: authenticationMethodConfigurations.GetCount-6d53
      parameters:
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
      responses:
        2XX:
          $ref: '#/components/responses/ODataCountResponse'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
